# newStep2_capture_cube_poses.py
"""
Step 2 (new): Capture ArUco cube images from gripper + fixed cameras
while communicating with robot server in cycle mode:

  내려놓기(place) -> 위로 상승(capture pose) -> 촬영

Key updates:
  1) Gripper camera connection checks (with fixed camera count guard)
  2) Robot cycle protocol (capture_cycle) for repeated down/up capture
  3) Capture acceptance with minimum 1 marker (default)

Examples
--------
[로봇 사이클 모드]
python newStep2_capture_cube_poses.py \
  --root_folder ./data/session_new \
  --intrinsics_dir ./intrinsics \
  --use_robot \
  --robot_ip 192.168.0.23 --robot_port 12348 \
  --joint_file newjoints_handeye_cycle.json \
  --save_depth --show \
  --min_markers 1 --min_cams_with_cube 1

[수동 모드]
python newStep2_capture_cube_poses.py \
  --root_folder ./data/session_new \
  --intrinsics_dir ./intrinsics \
  --save_depth --show
"""

import argparse
import json
import os
import time
from typing import Any, Dict, List, Optional

import cv2

from aruco_cube import ArucoCubeTarget
from camera import RealSenseCamera
from config import CubeConfig
from newrobot_comm import RobotCycleClient, euler_deg_to_matrix


Pose6 = List[float]


def ensure_dir(p: str) -> str:
    os.makedirs(p, exist_ok=True)
    return p


def load_device_map(intr_dir: str):
    map_path = os.path.join(intr_dir, "device_map.json")
    if not os.path.exists(map_path):
        return None, None, None
    with open(map_path, "r") as f:
        m = json.load(f)
    serial_to_idx = m.get("serial_to_idx", {})
    gripper_cam_idx = m.get("gripper_cam_idx", None)
    return serial_to_idx, gripper_cam_idx, map_path


def parse_pose6(obj: Any) -> Optional[Pose6]:
    if obj is None:
        return None
    if isinstance(obj, list) and len(obj) == 6:
        try:
            return [float(x) for x in obj]
        except Exception:
            return None
    if isinstance(obj, dict):
        for k in ["pose_6dof", "capture_pose_6dof", "place_pose_6dof", "pose", "tcp_pose_6dof"]:
            if k in obj:
                p = parse_pose6(obj[k])
                if p is not None:
                    return p
        if all(k in obj for k in ["x", "y", "z", "rz", "ry", "rx"]):
            try:
                return [
                    float(obj["x"]),
                    float(obj["y"]),
                    float(obj["z"]),
                    float(obj["rz"]),
                    float(obj["ry"]),
                    float(obj["rx"]),
                ]
            except Exception:
                return None
    return None


def is_zero_pose6(p: Pose6) -> bool:
    return all(abs(float(x)) < 1e-9 for x in p)


def make_place_pose_from_capture(capture_pose: Pose6, auto_place_dz_mm: float) -> Pose6:
    out = [float(x) for x in capture_pose]
    out[2] = float(out[2] + auto_place_dz_mm)
    return out


def load_cycle_commands(path: str, auto_place_dz_mm: float) -> List[Dict[str, Any]]:
    """
    Supported input formats:
      1) New format (recommended):
         [{"place_pose_6dof":[...], "capture_pose_6dof":[...], ...}, ...]
      2) Legacy list format:
         [[d1..d6], [d1..d6], ...]
         -> interpreted as capture poses, place poses auto-generated by z offset.
      3) Stop marker:
         - list row [0,0,0,0,0,0]
         - dict {"action":"stop"}
    """
    with open(path, "r") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise RuntimeError("joint_file/cycle_file must be a JSON list")

    out: List[Dict[str, Any]] = []

    for i, row in enumerate(data):
        if isinstance(row, dict):
            action = str(row.get("action", "")).strip().lower()
            if action in ["stop", "quit", "end"] or bool(row.get("stop", False)):
                break

            place_pose = parse_pose6(row.get("place_pose_6dof"))
            capture_pose = parse_pose6(row.get("capture_pose_6dof"))

            # Backward compatibility for dict with one pose
            if capture_pose is None:
                capture_pose = parse_pose6(row)
            if capture_pose is None:
                print(f"[WARN] Skip row {i}: cannot parse capture pose")
                continue

            if place_pose is None:
                place_pose = make_place_pose_from_capture(capture_pose, auto_place_dz_mm)

            out.append({
                "cycle_index": int(row.get("cycle_index", i)),
                "place_pose_6dof": [float(x) for x in place_pose],
                "capture_pose_6dof": [float(x) for x in capture_pose],
                "source_row": row,
            })
            continue

        if isinstance(row, list):
            p = parse_pose6(row)
            if p is None:
                print(f"[WARN] Skip row {i}: invalid list pose")
                continue
            if is_zero_pose6(p):
                break

            cap_pose = [float(x) for x in p]
            place_pose = make_place_pose_from_capture(cap_pose, auto_place_dz_mm)
            out.append({
                "cycle_index": i,
                "place_pose_6dof": place_pose,
                "capture_pose_6dof": cap_pose,
                "source_row": row,
            })
            continue

        print(f"[WARN] Skip row {i}: unsupported row type={type(row)}")

    if len(out) == 0:
        raise RuntimeError(f"No valid cycle commands parsed from {path}")

    return out


def main():
    parser = argparse.ArgumentParser(
        description="Capture cube images from all cameras + robot cycle poses"
    )
    parser.add_argument("--root_folder", required=True)
    parser.add_argument("--intrinsics_dir", required=True)

    # Stream config
    parser.add_argument("--fps", type=int, default=15)
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)

    # Detection / acceptance
    parser.add_argument(
        "--min_markers",
        type=int,
        default=1,
        help="Minimum markers visible per camera to consider cube-visible",
    )
    parser.add_argument(
        "--min_cams_with_cube",
        type=int,
        default=1,
        help="Minimum number of cameras that must see cube to save a capture",
    )
    parser.add_argument(
        "--allow_capture_without_cube",
        action="store_true",
        help="Save capture regardless of marker visibility",
    )

    # Camera topology checks
    parser.add_argument(
        "--gripper_cam_idx_override",
        type=int,
        default=None,
        help="Override gripper cam idx if device_map is missing/wrong",
    )
    parser.add_argument(
        "--require_gripper_cam",
        dest="require_gripper_cam",
        action="store_true",
        help="Fail if gripper camera is not detected",
    )
    parser.add_argument(
        "--no_require_gripper_cam",
        dest="require_gripper_cam",
        action="store_false",
        help="Do not fail when gripper camera is not detected",
    )
    parser.set_defaults(require_gripper_cam=True)
    parser.add_argument(
        "--expected_fixed_cams",
        type=int,
        default=3,
        help="Expected number of fixed cameras",
    )

    # Auto-save/manual display options
    parser.add_argument("--auto_save", action="store_true")
    parser.add_argument("--stable_frames", type=int, default=3)
    parser.add_argument("--cooldown_ms", type=int, default=700)
    parser.add_argument("--save_depth", action="store_true")
    parser.add_argument("--show", action="store_true")

    # Robot cycle mode
    parser.add_argument("--use_robot", action="store_true")
    parser.add_argument("--robot_ip", type=str, default="192.168.0.23")
    parser.add_argument("--robot_port", type=int, default=12348)
    parser.add_argument(
        "--joint_file",
        type=str,
        default=None,
        help="Cycle JSON file (legacy name kept for compatibility)",
    )
    parser.add_argument(
        "--cycle_file",
        type=str,
        default=None,
        help="Alias of joint_file. If both set, cycle_file is used.",
    )
    parser.add_argument(
        "--auto_place_dz_mm",
        type=float,
        default=-60.0,
        help="If only capture pose is provided, place_pose.z = capture_pose.z + this offset",
    )
    parser.add_argument(
        "--settle_time",
        type=float,
        default=0.6,
        help="Extra wait(s) after server reports cycle_done before capture",
    )
    parser.add_argument("--done_timeout", type=float, default=20.0)
    parser.add_argument("--query_robot_tcp", dest="query_robot_tcp", action="store_true")
    parser.add_argument("--no_query_robot_tcp", dest="query_robot_tcp", action="store_false")
    parser.set_defaults(query_robot_tcp=True)
    parser.add_argument(
        "--allow_capture_pose_as_fallback",
        action="store_true",
        help="If TCP pose is missing, use capture_pose_6dof as robot pose fallback",
    )
    parser.add_argument(
        "--send_stop_on_finish",
        dest="send_stop_on_finish",
        action="store_true",
        help="Send {'action':'stop'} to robot server when cycles end",
    )
    parser.add_argument(
        "--no_send_stop_on_finish",
        dest="send_stop_on_finish",
        action="store_false",
    )
    parser.set_defaults(send_stop_on_finish=True)

    args = parser.parse_args()

    root = ensure_dir(args.root_folder)
    intr_dir = args.intrinsics_dir

    # Load device map
    serial_to_idx, gripper_cam_idx, map_path = load_device_map(intr_dir)
    if args.gripper_cam_idx_override is not None:
        gripper_cam_idx = int(args.gripper_cam_idx_override)

    devs = RealSenseCamera.list_devices()
    if len(devs) == 0:
        raise RuntimeError("No RealSense devices found.")

    if serial_to_idx is None:
        print("[WARN] No device_map.json. Run Step1 first. Using fallback serial sort.")
        serials = sorted(devs.keys())
        idx_serial_pairs = [(i, s) for i, s in enumerate(serials)]
    else:
        idx_serial_pairs = []
        for serial in devs.keys():
            if serial in serial_to_idx:
                idx_serial_pairs.append((int(serial_to_idx[serial]), serial))
        idx_serial_pairs.sort(key=lambda x: x[0])

    if len(idx_serial_pairs) == 0:
        raise RuntimeError("No usable cameras found.")

    # Camera topology checks
    found_cam_ids = sorted([int(ci) for ci, _ in idx_serial_pairs])
    if args.require_gripper_cam:
        if gripper_cam_idx is None:
            raise RuntimeError(
                "gripper_cam_idx is unknown. Use Step1 --gripper_serial or --gripper_cam_idx_override"
            )
        if gripper_cam_idx not in found_cam_ids:
            raise RuntimeError(
                f"gripper cam idx cam{gripper_cam_idx} is not connected. connected={found_cam_ids}"
            )

    fixed_cam_ids = [ci for ci in found_cam_ids if ci != gripper_cam_idx]
    if len(fixed_cam_ids) < int(args.expected_fixed_cams):
        print(
            f"[WARN] Fixed camera count is lower than expected: "
            f"found={len(fixed_cam_ids)} expected={args.expected_fixed_cams}"
        )

    print("[INFO] Cameras:")
    for idx, s in idx_serial_pairs:
        tag = "GRIPPER" if idx == gripper_cam_idx else "FIXED"
        print(f"  cam{idx}: {s} ({tag})")
    print(f"[INFO] gripper_cam_idx={gripper_cam_idx} fixed_cam_ids={fixed_cam_ids}")
    if map_path:
        print(f"[INFO] device_map={map_path}")

    # Start cameras
    cams: Dict[int, RealSenseCamera] = {}
    for ci, serial in idx_serial_pairs:
        cam = RealSenseCamera(
            serial=serial,
            width=args.width,
            height=args.height,
            fps=args.fps,
            use_color=True,
            use_depth=args.save_depth,
            align_depth_to_color=True,
            warmup_frames=10,
        )
        cam.start()
        cams[ci] = cam
        ensure_dir(os.path.join(root, f"cam{ci}"))

    cfg = CubeConfig()
    cube = ArucoCubeTarget(cfg)

    # Robot setup
    robot_client: Optional[RobotCycleClient] = None
    cycle_cmds: List[Dict[str, Any]] = []

    if args.use_robot:
        cycle_file = args.cycle_file or args.joint_file
        if not cycle_file:
            raise RuntimeError("--use_robot requires --cycle_file or --joint_file")

        cycle_cmds = load_cycle_commands(cycle_file, auto_place_dz_mm=float(args.auto_place_dz_mm))
        print(f"[INFO] Loaded {len(cycle_cmds)} cycle commands from {cycle_file}")

        robot_client = RobotCycleClient(args.robot_ip, args.robot_port)
        robot_client.connect()

    # Meta
    meta = {
        "root_folder": os.path.abspath(root),
        "gripper_cam_idx": gripper_cam_idx,
        "fixed_cam_ids": [int(x) for x in fixed_cam_ids],
        "capture_protocol": "capture_cycle_v1",
        "capture_settings": {
            "min_markers": int(args.min_markers),
            "min_cams_with_cube": int(args.min_cams_with_cube),
            "allow_capture_without_cube": bool(args.allow_capture_without_cube),
        },
        "captures": [],
    }
    meta_path = os.path.join(root, "meta.json")

    event_id = 0
    stable_cnt = {ci: 0 for ci in cams}
    last_save_t = 0.0

    print("\nControls:")
    print("  SPACE : manual capture (visibility check)")
    print("  ESC/q : quit\n")

    def do_capture(
        robot_pose_6dof: Optional[Pose6] = None,
        robot_pose_source: Optional[str] = None,
        cycle_info: Optional[Dict[str, Any]] = None,
        robot_done_packet: Optional[Dict[str, Any]] = None,
    ) -> bool:
        """Capture from all cameras. Returns True if successful."""
        nonlocal event_id, last_save_t

        frames: Dict[int, Dict[str, Any]] = {}
        cams_with_cube = 0

        for ci, cam in cams.items():
            color, depth, ts_ms = cam.get_latest()
            if color is None:
                continue

            corners, ids = cube.detect(color)
            ok = (ids is not None) and (len(ids) >= int(args.min_markers))
            if ok:
                cams_with_cube += 1

            frames[ci] = {
                "color": color,
                "depth": depth,
                "ts_ms": ts_ms,
                "ok": bool(ok),
                "ids": ([] if ids is None else [int(x) for x in ids]),
                "corners": corners,
                "ids_np": ids,
            }

        if (not args.allow_capture_without_cube) and (cams_with_cube < int(args.min_cams_with_cube)):
            print(f"[SKIP] Only {cams_with_cube}/{args.min_cams_with_cube} cams see cube")
            return False

        fid = int(event_id)
        cap_rec: Dict[str, Any] = {
            "event_id": fid,
            "cams": {},
            "cams_with_cube": int(cams_with_cube),
        }

        if cycle_info is not None:
            cap_rec["cycle_index"] = int(cycle_info.get("cycle_index", fid))
            cap_rec["place_pose_6dof"] = [float(x) for x in cycle_info["place_pose_6dof"]]
            cap_rec["capture_pose_6dof"] = [float(x) for x in cycle_info["capture_pose_6dof"]]

        if robot_pose_6dof is not None:
            pose6 = [float(x) for x in robot_pose_6dof]
            cap_rec["robot_pose_6dof"] = pose6
            cap_rec["robot_pose_source"] = str(robot_pose_source or "unknown")
            try:
                cap_rec["robot_pose_matrix_4x4"] = euler_deg_to_matrix(*pose6).tolist()
            except Exception:
                pass

        if robot_done_packet is not None:
            cap_rec["robot_done_packet"] = robot_done_packet

        for ci in sorted(frames.keys()):
            fr = frames[ci]
            rgb_rel = f"cam{ci}/rgb_{fid:05d}.jpg"
            cv2.imwrite(os.path.join(root, rgb_rel), fr["color"])

            depth_rel = None
            if args.save_depth and fr["depth"] is not None:
                depth_rel = f"cam{ci}/depth_{fid:05d}.png"
                cv2.imwrite(os.path.join(root, depth_rel), fr["depth"])

            cap_rec["cams"][str(ci)] = {
                "saved": True,
                "ts_ms": fr["ts_ms"],
                "rgb_path": rgb_rel,
                "depth_path": depth_rel,
                "ids": fr["ids"],
                "cube_visible": fr["ok"],
            }

        meta["captures"].append(cap_rec)
        with open(meta_path, "w") as f:
            json.dump(meta, f, indent=2)

        visible_str = ", ".join([
            f"cam{ci}({'Y' if frames[ci]['ok'] else 'N'})" for ci in sorted(frames.keys())
        ])
        src = cap_rec.get("robot_pose_source", "-")
        print(f"[SAVE] event_id={event_id} | {visible_str} | pose_src={src}")

        event_id += 1
        last_save_t = time.time() * 1000.0
        return True

    try:
        if args.use_robot:
            print("[MODE] Robot cycle capture (place -> lift -> capture)")

            for cmd in cycle_cmds:
                cycle_idx = int(cmd.get("cycle_index", -1))
                place_pose = cmd["place_pose_6dof"]
                capture_pose = cmd["capture_pose_6dof"]

                print(
                    f"\n[RobotCycle] idx={cycle_idx} "
                    f"place={place_pose} capture={capture_pose}"
                )

                ok, tcp_pose, pose_source, done_pkt = robot_client.send_cycle_and_wait(
                    place_pose_6dof=place_pose,
                    capture_pose_6dof=capture_pose,
                    cycle_index=cycle_idx,
                    post_done_wait=float(args.settle_time),
                    query_tcp_if_missing=bool(args.query_robot_tcp),
                    done_timeout=float(args.done_timeout),
                )
                if not ok:
                    print("[INFO] Robot quit or cycle error. stop capture loop")
                    break

                if tcp_pose is None and args.allow_capture_pose_as_fallback:
                    print("[WARN] TCP pose missing. Using capture_pose_6dof as fallback")
                    tcp_pose = [float(x) for x in capture_pose]
                    pose_source = "capture_pose_fallback"
                elif tcp_pose is None:
                    print("[WARN] TCP pose missing. capture saved without robot_pose_6dof")

                do_capture(
                    robot_pose_6dof=tcp_pose,
                    robot_pose_source=pose_source,
                    cycle_info=cmd,
                    robot_done_packet=done_pkt,
                )

            if robot_client is not None and args.send_stop_on_finish:
                try:
                    robot_client.send_stop()
                    print("[INFO] Sent stop action to robot server")
                except Exception:
                    pass

            print(f"\n[DONE] Robot cycle capture complete. {event_id} captures saved.")

        else:
            print("[MODE] Manual capture (press SPACE)")
            while True:
                frames_view: Dict[int, Dict[str, Any]] = {}
                for ci, cam in cams.items():
                    color, _, _ = cam.get_latest()
                    if color is None:
                        continue

                    corners, ids = cube.detect(color)
                    ok = (ids is not None) and (len(ids) >= int(args.min_markers))
                    if ok:
                        stable_cnt[ci] += 1
                    else:
                        stable_cnt[ci] = 0

                    frames_view[ci] = {
                        "color": color,
                        "ok": ok,
                        "corners": corners,
                        "ids_np": ids,
                    }

                if args.show:
                    for ci in sorted(frames_view.keys()):
                        img = frames_view[ci]["color"].copy()
                        ids_np = frames_view[ci]["ids_np"]
                        corners = frames_view[ci]["corners"]
                        if ids_np is not None:
                            try:
                                draw_ids = ids_np.reshape(-1, 1) if getattr(ids_np, "ndim", 1) == 1 else ids_np
                                cv2.aruco.drawDetectedMarkers(img, corners, draw_ids)
                            except Exception:
                                pass

                        tag = "GRIP" if ci == gripper_cam_idx else "FIX"
                        txt = f"cam{ci}({tag}) ok={frames_view[ci]['ok']} stable={stable_cnt[ci]}"
                        cv2.putText(img, txt, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
                        cv2.imshow(f"cam{ci}", img)

                key = cv2.waitKey(1) & 0xFF
                now_ms = time.time() * 1000.0

                if key == 27 or key == ord("q"):
                    break

                manual_trigger = (key == 32)  # SPACE

                if args.auto_save:
                    all_stable = all(stable_cnt.get(ci, 0) >= int(args.stable_frames) for ci in cams)
                    if all_stable and (now_ms - last_save_t) >= float(args.cooldown_ms):
                        manual_trigger = True

                if manual_trigger:
                    do_capture(robot_pose_6dof=None)

    finally:
        for cam in cams.values():
            cam.stop()
        if robot_client:
            robot_client.close()
        cv2.destroyAllWindows()

    print(f"\n[DONE] Total captures: {event_id}")
    print(f"  Meta saved: {meta_path}")


if __name__ == "__main__":
    main()
